
1、资源类型表
CREATE TABLE `biz_res_type` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '数据库主键',
  `PARENT_DB_ID` VARCHAR(50) DEFAULT NULL COMMENT '上级节点',
  `CODE` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '编码',
  `NAME` VARCHAR(100) DEFAULT NULL COMMENT '名称',   
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`),
  UNIQUE KEY `IDX_RES_TYPE_CODE` (`CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='资源类型表';

2、资源分类类型表
CREATE TABLE `biz_res_cat_type` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '复分类型主键',
  `CODE` VARCHAR(20) NOT NULL COMMENT '复分类型编码',
  `NAME` VARCHAR(50) DEFAULT NULL COMMENT '复分类型名称',
  `PARENT_DB_ID` VARCHAR(50) DEFAULT NULL COMMENT '父ID',
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`),
  UNIQUE KEY `IDX_CAT_TYPE_CODE` (`CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='资源分类类型表';

3、资源AC主分类表
CREATE TABLE `biz_res_cat_master` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT 'AC主分类唯一标识',
  `RES_TYPE_DB_ID` VARCHAR(50) DEFAULT NULL COMMENT '所属资源类型DB_ID', 
  `CODE` VARCHAR(20) NOT NULL COMMENT '分类编码',
  `NAME` VARCHAR(50) DEFAULT NULL COMMENT '主分名称', 
  `PARENT_DB_ID` VARCHAR(50) DEFAULT '' COMMENT '父AC主分类唯一标识',
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`),
  UNIQUE KEY `IDX_CAT_CODE` (`CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8  COMMENT='资源AC主分表';

4、资源复分类表
CREATE TABLE `biz_res_cat_second` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '主键',
  `CODE` VARCHAR(20) NOT NULL COMMENT '编码',  
  `TYPE_DB_ID` VARCHAR(50) DEFAULT NULL COMMENT '所属类型ID',
  `NAME` VARCHAR(50) DEFAULT NULL COMMENT '复分名称',
  `PARENT_DB_ID` VARCHAR(50) DEFAULT NULL COMMENT '上级节点',
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`),
  UNIQUE KEY `IDX_CAT_SEC_CODE` (`CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='资源AC复分表';

5、资源主分类与复分类关联表
CREATE TABLE `biz_res_cat_r` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '主键',
  `MASTER_DB_ID` VARCHAR(50) DEFAULT NULL COMMENT '主分类ID',
  `SECOND_DB_ID` VARCHAR(50) DEFAULT NULL COMMENT '复分类ID', 
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`),
  UNIQUE KEY `IDX_CAT_R` (`MASTER_DB_ID`, `SECOND_DB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='资源主分类与复分类关联表';

5、文物表
CREATE TABLE `biz_res_heritage` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '主键',
  `CODE` VARCHAR(20) NOT NULL COMMENT '编码',   
  `NAME` VARCHAR(200) DEFAULT NULL COMMENT '名称', 
  `LANG` VARCHAR(50) DEFAULT NULL COMMENT '语种, 默认中文', 
  `CONTENT` MEDIUMBLOB COMMENT '内容。JSON格式文本内容', 
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='文物资源表';

6、古籍表
CREATE TABLE `biz_res_ancient` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '主键',
  `CODE` VARCHAR(20) NOT NULL COMMENT '编码',   
  `NAME` VARCHAR(200) DEFAULT NULL COMMENT '名称', 
  `LANG` VARCHAR(50) DEFAULT NULL COMMENT '语种, 默认中文', 
  `CONTENT` MEDIUMBLOB COMMENT '内容。JSON格式文本内容', 
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='古籍资源表';

7、展览表
CREATE TABLE `biz_res_exhibition` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '主键',
  `CODE` VARCHAR(20) NOT NULL COMMENT '编码',   
  `NAME` VARCHAR(200) DEFAULT NULL COMMENT '名称', 
  `LANG` VARCHAR(50) DEFAULT NULL COMMENT '语种, 默认中文', 
  `CONTENT` MEDIUMBLOB COMMENT '内容。JSON格式文本内容', 
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='展览资源表';

8、影像表
CREATE TABLE `biz_res_video` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '主键',
  `CODE` VARCHAR(20) NOT NULL COMMENT '编码',   
  `NAME` VARCHAR(200) DEFAULT NULL COMMENT '名称', 
  `LANG` VARCHAR(50) DEFAULT NULL COMMENT '语种, 默认中文', 
  `CONTENT` MEDIUMBLOB COMMENT '内容。JSON格式文本内容', 
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='影像资源表';

9、保护修复表
CREATE TABLE `biz_res_restoration` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '主键',
  `CODE` VARCHAR(20) NOT NULL COMMENT '编码',   
  `NAME` VARCHAR(200) DEFAULT NULL COMMENT '名称', 
  `LANG` VARCHAR(50) DEFAULT NULL COMMENT '语种, 默认中文', 
  `CONTENT` MEDIUMBLOB COMMENT '内容。JSON格式文本内容', 
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='保护修复资源表';

10、综合数据表
CREATE TABLE `biz_res_comprehensive` (
  `DB_ID` VARCHAR(50) NOT NULL COMMENT '主键',
  `CODE` VARCHAR(20) NOT NULL COMMENT '编码',   
  `NAME` VARCHAR(200) DEFAULT NULL COMMENT '名称', 
  `LANG` VARCHAR(50) DEFAULT NULL COMMENT '语种, 默认中文', 
  `CONTENT` MEDIUMBLOB COMMENT '内容。JSON格式文本内容', 
  `CREATED_DT` DATETIME COMMENT '创建时间',
  `STATUS` INT DEFAULT '1' COMMENT '状态，1 启用 0 禁用 默认为启用',
  `VERSION` INT DEFAULT '0' COMMENT '并发版本控制',
  `TAB_INDEX` INT DEFAULT '0' COMMENT '排序码',
  PRIMARY KEY (`DB_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='综合数据资源表';
