--工作流流程节点设置表  
CREATE TABLE TBL_CORE_ACT_NODE (	
 DB_ID 						VARCHAR(50) 	NOT NULL COMMENT '主键', 
 PROCESSDEFINITION_KEY 		VARCHAR(100) 	DEFAULT '' COMMENT '流程定义唯一标识符', 
 PROCESSDEFINITION_NAME 	VARCHAR(200) 	DEFAULT '' COMMENT '流程定义名称', 
 ACTIVITY_ID 				VARCHAR(100) 	DEFAULT '' COMMENT '节点ID', 
 ACTIVITY_NAME 				VARCHAR(200) 	DEFAULT '' COMMENT '节点名称', 
 ACTIVITY_TYPE 				VARCHAR(50) 	DEFAULT '' COMMENT '节点类型', 
 FORM_URL	 				VARCHAR(100) 	DEFAULT '' COMMENT '业务表单URL', 
 IS_MULTI_TASK 				INT 			DEFAULT 0 COMMENT '是否为多实例任务', 
 IS_SEQUENTIAL				INT				DEFAULT 0 COMMENT '是否顺序执行多实例任务',
 MUL_INS_COMPLET_CONDITION 	VARCHAR(20) 	DEFAULT '' COMMENT '多实例任务完成条件', 
 TASK_LISTENER 				VARCHAR(500) COMMENT '事件监听器,JSON格式', 
 VARIABLE_EXPRESSION 		VARCHAR(500) COMMENT '变量表达式，JSON格式', 
 PRIMARY KEY (DB_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工作流流程节点设置表';
 
--工作流流程节点参与者表  
CREATE TABLE TBL_CORE_ACT_ASSIGNEES (	
 DB_ID 					VARCHAR(50) 	NOT NULL COMMENT '主键',
 NODE_DB_ID 			VARCHAR(50) 	NOT NULL COMMENT '流程节点设置表主键(TBL_CORE_ACTIVITY_NODE的DB_ID)',
 ASSIGNEE_DB_ID 		VARCHAR(50) 	DEFAULT '' COMMENT '节点参与值DB_ID',
 ASSIGNEE_ID 			VARCHAR(100) 	DEFAULT '' COMMENT '节点参与值ID',
 ASSIGNEE_NAME	 		VARCHAR(200) 	DEFAULT '' COMMENT '节点参与者名称', 
 ASSIGNEE_TYPE			VARCHAR(10) 	DEFAULT '' COMMENT '节点参与者类型: USER, ROLE, GROUP',  
 STATUS 				INT 			DEFAULT 1 COMMENT '',
 PRIMARY KEY (DB_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工作流流程节点参与者表';

--流程回退操作日志表
CREATE TABLE TBL_CORE_BACK_LOG (
 DB_ID 						VARCHAR(50) 	NOT NULL COMMENT '主键',
 PROCESSDEFINITION_ID 		VARCHAR(100) 	NOT NULL  COMMENT '流程模型ID',
 PROCESSINSTANCE_ID 		VARCHAR(100) 	NOT NULL  COMMENT '流程实例ID',
 ACTIVITY_ID_FROM 			VARCHAR(100) 	NOT NULL COMMENT '退回时的流程节点ID',
 ACTIVITY_NAME_FROM			VARCHAR(200)   COMMENT '退回时的流程节点名称',
 ACTIVITY_ID_TO 			VARCHAR(100) 	NOT NULL COMMENT '退回到的流程节点ID',
 ACTIVITY_NAME_TO			VARCHAR(200)	 COMMENT'退回到的流程节点名称' ,
 OPERATOR 					VARCHAR(100) 	NOT NULL COMMENT '操作：BACK（退回） CANCEL (撤销) ',
 CREATE_TIME 				DATETIME			DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间' ,
 IN_USE 					CHAR(1) 		DEFAULT 'Y' COMMENT '是否有效，Y 有效， N 无效' ,
 VERSION 					INT 			DEFAULT 0 COMMENT '并发操作的锁' , 
  PRIMARY KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='流程回退操作日志表';
 
--系统全局变量表
CREATE TABLE  TBL_CORE_COMMON (  
 NAME 		VARCHAR(200) DEFAULT '' COMMENT '名称',
 VALUE_ 	VARCHAR(200) DEFAULT ''  COMMENT '值',
 TYPE_ 		VARCHAR(200) DEFAULT ''  COMMENT '类型',
 STATUS 	INT DEFAULT 1  COMMENT '状态: 1 启用;  0 禁用; 默认 1',
 TAB_INDEX 	INT DEFAULT 0  COMMENT '显示顺序',
 PRIMARY KEY (NAME) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统全局变量表';

--数据源设置表
CREATE TABLE  TBL_CORE_DATASOURCE (  
 DB_ID  			VARCHAR(50) 	NOT NULL COMMENT '主键',
 DS_KEY 			VARCHAR(100)  NOT NULL  COMMENT '数据源标识名',
 DB_TYPE 			VARCHAR(50) DEFAULT ''  COMMENT '数据库类型',
 DB_NAME 			VARCHAR(50) DEFAULT ''  COMMENT '数据库名称',
 DRIVER_CLASS 		VARCHAR(100) DEFAULT ''  COMMENT '数据库驱动类',
 JDBC_URL 			VARCHAR(100) DEFAULT ''  COMMENT '数据库连接地址',
 JDBC_USER 			VARCHAR(50) DEFAULT ''  COMMENT '数据库用户名',
 JDBC_PASSWORD 		VARCHAR(50) DEFAULT ''  COMMENT '数据库密码', 
 INIT_POOL_SIZE		INT COMMENT '数据库连接池初始值',
 MIN_POOL_SIZE		INT COMMENT '数据库连接池最小值',
 MAX_POOL_SIZE		INT COMMENT '数据库连接池最大值',
 STATUS 			INT DEFAULT 1  COMMENT '状态: 1 启用;  0 禁用; 默认 1',
 TAB_INDEX 			INT DEFAULT 0  COMMENT '显示顺序',
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDX_DSKEY` (`DS_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据源设置表';
 
-- 数据权限配置表
CREATE TABLE TBL_CORE_DATA_AUTHORITY (
 DB_ID 						VARCHAR(50) NOT NULL COMMENT '数据库主键',
 REF_R_DB_ID				VARCHAR(50) COMMENT '数据表TBL_CORE_DATA_REF_R主键',
 DEF_DB_ID 					VARCHAR(50) NOT NULL COMMENT '数据表TBL_WF_DATA_DEF主键',
 COLUMN_DB_ID 				VARCHAR(50) COMMENT '数据表TBL_WF_DATA_COLUMN主键',
 AUTHED_DB_ID 				VARCHAR(50)  COMMENT '被授权者主键',
 AUTH_TYPE 					VARCHAR(10) NOT NULL  COMMENT '授权类型（用户、角色或者用户组）',
 DATA_TYPE 					VARCHAR(10) DEFAULT 'COMMON' COMMENT '数据类型，基础数据OR业务数据（COMMON OR BUSINESS）', 
 STATUS 					INT DEFAULT 1 COMMENT '状态，1 启用 0 禁用，默认启用', 
 PRIMARY KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据权限设置表';
 
--基础数据权限要素值
CREATE TABLE TBL_CORE_DATA_AUTHORITY_VALUE
(	
    DB_ID   			VARCHAR(50)   	NOT NULL COMMENT '数据库主键',
	AUTHORITY_DB_ID 	VARCHAR(50) 	NOT NULL COMMENT '权限要素设置表TBL_WF_DATA_AUTH_CONFIG的主键' , 
	DATA_VALUE 			VARCHAR(200) 	NOT NULL COMMENT  '授权数据的值',
	STATUS 				INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用，默认启用',
	PRIMARY KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据权限设置表';
 

--业务数据详细字段表 
CREATE TABLE TBL_CORE_DATA_COLUMN
(	
   	DB_ID 				VARCHAR(50) 	NOT NULL COMMENT '数据库自增，主键', 
	DEF_DB_ID 			VARCHAR(50) 	NOT NULL COMMENT '数据定义表主键', 
	CODE 				VARCHAR(100) 	NOT NULL COMMENT '字段编码', 
	NAME 				VARCHAR(200) 	NOT NULL COMMENT '字段名称', 
	BEAN_FIELD_NAME		VARCHAR(100) 	NOT NULL COMMENT '字段别名', 
	FIELD_SIZE 			INT 			NOT NULL COMMENT '字段长度', 
	FIELD_PRECISION		INT 			DEFAULT 0 COMMENT '字段精度', 
	FIELD_TYPE 			VARCHAR(50) 	DEFAULT '' COMMENT '字段类型', 
	DEFAULT_VALUE	 	VARCHAR(200) COMMENT '字段的默认值', 
	FIELD_COMMENT 		VARCHAR(500) COMMENT '字段注释', 
	PRIMARY_FIELD 		INT 			DEFAULT 0 COMMENT '是否是主键，1为主键 ；0为否， 默认为非主键', 
	QUOTE_FIELD			INT 			DEFAULT 0 COMMENT '是否为引用字段，1为是 ；0为否， 默认为否', 
	DISPLAY_FIELD		INT 			DEFAULT 0 COMMENT '是否为显示字段，1为是 ；0为否， 默认为是', 
	TREE_FIELD			INT 			DEFAULT 0 COMMENT '是否树节点，1为是 ；0为否， 默认为否', 
	RESOURCE_TYPE_CODE	VARCHAR(50) COMMENT '资源类型与TBL_WF_RESOURCE_TYPE关联',  
	MARK 				VARCHAR(1000) COMMENT '备注说明信息', 
	QUERY_FIELD			INT 			DEFAULT 0 COMMENT '是否是查询条件，1为是 ；0为否， 默认为否', 
	MANDATORY_FIELD 	INT 			DEFAULT 0 COMMENT '是否为必须输入字段，1为是 ；0为否， 默认为是', 
	VALID_TYPE			VARCHAR(100) COMMENT '验证类型',
	MISSING_MESSAGE		VARCHAR(500) COMMENT '提示信息',
	INVALID_MESSAGE		VARCHAR(500) COMMENT '无效提示信息', 
	MIN_VALUE			VARCHAR(100) COMMENT '最小值',
	MAX_VALUE			VARCHAR(100) COMMENT '最大值',
	PRECISION_VALUE		VARCHAR(100) COMMENT '精度',
	DATA_OPTIONS		VARCHAR(200) COMMENT '自定义验证类型',
	UNIQUE_FIELD		INT 			DEFAULT 0 COMMENT '是否唯一，1为是 ；0为否， 默认为否', 
	STATUS				INT DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用', 
	VERSION				INT DEFAULT 0 COMMENT '并发版本控制', 
	TAB_INDEX			INT DEFAULT 0 COMMENT '显示顺序', 
	PRIMARY KEY (DB_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='业务数据详细字段表';

--业务数据定义
CREATE TABLE TBL_CORE_DATA_DEF
(
 DB_ID 						VARCHAR(50) 		NOT NULL COMMENT '数据库主键',
 ORG_DB_ID 					VARCHAR(50)  COMMENT '所属机构', 
 MENU_DB_ID 				VARCHAR(50)  COMMENT '功能菜单', 
 CODE 						VARCHAR(100) 		NOT NULL  COMMENT '业务数据编码', 
 NAME 						VARCHAR(200)  COMMENT '业务数据名称',
 DATA_TYPE 					VARCHAR(50) COMMENT '数据类型(业务数据 OR 基础数据)',
 AUTH_ENABLE				VARCHAR(10)	DEFAULT 'N' COMMENT '是否是权限控制要素, Y : 是; N : 否',
 TABLE_NAME 				VARCHAR(100)  COMMENT '对应的数据库表名称',
 TABLE_COMMENTS 			VARCHAR(1000) COMMENT '对应的数据库表注释',
 MODEL_NAME 				VARCHAR(100)  COMMENT '模块名称',
 PACKAGE_NAME 				VARCHAR(100)  COMMENT '包名',
 CURRENT_YEAR 				VARCHAR(10)  COMMENT '当前年度',
 TREE_TABLE 				INT 				DEFAULT 0  COMMENT '是否树形结构',
 STATUS 					INT 				DEFAULT 1  COMMENT , 
 VERSION 					INT 				DEFAULT 0  COMMENT '并发版本控制', 
 TAB_INDEX					INT					DEFAULT 0 COMMENT '排序码',
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDX_DEF_CODE` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据定义表';

--数据与事件关联表
CREATE TABLE TBL_CORE_DATA_EVENT_R  (
   DB_ID                VARCHAR(50)  	NOT NULL COMMENT '主键',
   DEF_DB_ID            VARCHAR(50) 	NOT NULL COMMENT '数据表主键',
   EVENT_DB_ID   		VARCHAR(50)  	NOT NULL COMMENT '事件表主键',
   STATUS 				INT 			DEFAULT 1  COMMENT '状态，1 启用 0 禁用 默认为启用' ,
   PRIMARY KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据与事件关联表';
 
--数据引用关系表
CREATE TABLE TBL_CORE_DATA_REF_R  (
	DB_ID				VARCHAR(50)    NOT NULL COMMENT '主键',
	DEF_DB_ID			VARCHAR(50)	NOT NULL COMMENT '数据表TBL_WF_DATA_DEF主键',
	COLUMN_DB_ID		VARCHAR(50)	NOT NULL COMMENT '数据表TBL_WF_DATA_COLUMN主键',
	REF_DB_ID			VARCHAR(50)	NOT NULL COMMENT '引用数据表TBL_WF_DATA_COLUMN主键',
	REF_COLUMN_DB_ID	VARCHAR(50)	NOT NULL COMMENT '引用数据表TBL_WF_DATA_COLUMN主键',
	DATA_AUTH_ENABLE	VARCHAR(10)	DEFAULT 'N' COMMENT '是否启用数据权限标志。 Y：启用； N：禁用； 默认N',
	PROCESS_AUTH_ENABLE	VARCHAR(10)	DEFAULT 'N' COMMENT '是否用流程权限标志。 Y：启用； N：禁用； 默认N',
	PRIMARY KEY(DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据引用关系表'; 

--数据与变量关联表
CREATE TABLE TBL_CORE_DATA_VARIABLE_R  (
   DB_ID                VARCHAR(50)  	NOT NULL COMMENT '主键',
   DEF_DB_ID            VARCHAR(50) 	NOT NULL COMMENT '数据表主键',
   VAR_DB_ID   			VARCHAR(50)  	NOT NULL COMMENT '变量表主键',
   STATUS 				INT 			DEFAULT 1  COMMENT '状态，1 启用 0 禁用 默认为启用',
   PRIMARY KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据与变量关联表'; 

--事件
CREATE TABLE TBL_CORE_EVENT  
(
   DB_ID                VARCHAR(50)  	NOT NULL COMMENT '主键',
   CODE            		VARCHAR(100) 	NOT NULL COMMENT '编码',
   NAME   				VARCHAR(100) COMMENT '名称', 
   SYSTEM_ID			VARCHAR(50) COMMENT '系统',
   CLASS_NAME         	VARCHAR(100) COMMENT 'JAVA类名',
   SPRING_BEAN_ID 		VARCHAR(100) COMMENT 'SPRING中ID',
   METHOD_NAME          VARCHAR(50) COMMENT '方法名',
   STATUS 				INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用' ,
   EVENT_TYPE           VARCHAR(50), 
   PRIMARY KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='事件表'; 

--用户组
CREATE TABLE TBL_CORE_GROUP (
 DB_ID 				VARCHAR(50) 	NOT NULL COMMENT  '数据库主键', 
 ID 				VARCHAR(100) 	NOT NULL COMMENT  '唯一标识',
 NAME	 			VARCHAR(200) 	DEFAULT '' COMMENT '中文名称',
 DESCRIPTION 		VARCHAR(1000) 	DEFAULT '' COMMENT '描述',
 CREATED_DT 		DATETIME COMMENT '创建时间',
 VERSION 			INT 			DEFAULT 0 COMMENT '并发版本控制',
 STATUS 			INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用' ,
 TAB_INDEX 			INT 			DEFAULT 0 COMMENT '排序码',
 PRIMARY KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户组表';  

--用户组与功能菜单关联表
CREATE TABLE TBL_CORE_GROUP_MENU_R (
 DB_ID 			VARCHAR(50) NOT NULL  COMMENT '数据库主键',
 MENU_DB_ID 	VARCHAR(50) NOT NULL COMMENT '功能菜单',
 GROUP_DB_ID 	VARCHAR(50) NOT NULL COMMENT '用户组',
 STATUS 		INT 		DEFAULT 1 COMMENT  '状态，1 启用 0 禁用，默认启用' , 
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDINX_GROUP_MENU_R` (`MENU_DB_ID`,`GROUP_DB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色与功能菜单关联表';  

--用户组与角色的关联表
CREATE TABLE TBL_CORE_ROLE_GROUP_R (
 DB_ID 			VARCHAR(50) 	NOT NULL COMMENT '数据库主键',
 GROUP_DB_ID 	VARCHAR(50) 	NOT NULL COMMENT '用户组表数据库自增，主键',
 ROLE_DB_ID 	VARCHAR(50) 	NOT NULL COMMENT  '角色表数据库自增，主键' ,
 STATUS 		INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用', 
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDX_GROUP_ROLE_R` (`GROUP_DB_ID`,`ROLE_DB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户组与角色的关联表'; 

--序列号
CREATE TABLE TBL_CORE_ID (
 DB_ID      VARCHAR(50) NOT NULL,
 KEY_ 		VARCHAR(255) NOT NULL COMMENT '生成序列号KEY',
 VALUE_ 	VARCHAR(255) DEFAULT NULL COMMENT '当前序列号值', 
 PRIMARY 	KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='序列号表'; 

--日志表
CREATE TABLE TBL_CORE_LOG (
 DBID 						VARCHAR(50) 	NOT NULL COMMENT '主键' ,
 MODELNAME				 	VARCHAR(200) 	NOT NULL COMMENT '模块名',
 USERID 					VARCHAR(100) 	NOT NULL COMMENT '操作者ID',
 USERNAME 					VARCHAR(1000) 	NOT NULL COMMENT '操作者名称',
 OPERATOR					VARCHAR(1000) COMMENT '操作',
 BUSINESSKEY				VARCHAR(50)	NOT NULL COMMENT '业务主键', 
 OPERATETIME 				DATETIME COMMENT '操作时间', 
  PRIMARY KEY (DBID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='业务操作日志表'; 

--功能菜单表
CREATE TABLE TBL_CORE_MENU (
 DB_ID 			VARCHAR(50) 	NOT NULL COMMENT '数据库主键',
 PARENT_DB_ID 	VARCHAR(50)  	DEFAULT 0 COMMENT '上级节点数据库DB_ID' ,
 ORG_DB_ID 		VARCHAR(50) COMMENT  '所属机构数据库主键',
 ID 			VARCHAR(100) 	NOT NULL COMMENT  '资源标识符',
 NAME 			VARCHAR(200) 	DEFAULT '' COMMENT '资源名称', 
 URL 			VARCHAR(500) 	DEFAULT '' COMMENT '连接地址', 
 MENU_TYPE		VARCHAR(20) COMMENT '菜单类型',	
 IS_LEAF 		INT 			DEFAULT 0 COMMENT '是否叶子节点，1 是 0 否，默认否',
 VERSION 			INT 			DEFAULT 0 COMMENT '并发版本控制',
 STATUS 			INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用' ,
 TAB_INDEX 			INT 			DEFAULT 0 COMMENT '排序码',
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDX_MENU_ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='功能菜单表';  

--流程回退操作日志表
CREATE TABLE TBL_CORE_MESSAGE (
 DB_ID 						VARCHAR(50) 	NOT NULL  COMMENT '主键' ,
 TITLE				 		VARCHAR(200) 	NOT NULL COMMENT '标题',
 SENDER 					VARCHAR(100) 	NOT NULL COMMENT '发送者',
 RECEIVER 					VARCHAR(1000) 	NOT NULL COMMENT '接收者',
 CONTENT					VARCHAR(1000) COMMENT '内容',
 SEND_TIME 					DATETIME COMMENT '发送时间',
 CREATE_TIME 				DATETIME 	DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 STATUS 					INT 		DEFAULT 0 COMMENT '发送状态。1：已发送；0：未发送', 
  PRIMARY KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统信息表';  

--机构--机构
CREATE TABLE TBL_CORE_ORG (
 DB_ID 				VARCHAR(50) 	NOT NULL COMMENT '数据库主键', 
 PARENT_DB_ID		VARCHAR(50)    NOT NULL COMMENT '上级节点',
 CATEGORY_DB_ID		VARCHAR(50) COMMENT '机构分类',
 ID 				VARCHAR(100) 	NOT NULL  COMMENT  '唯一标识',
 NAME 				VARCHAR(200) 	DEFAULT '' COMMENT '中文名称',
 ENNAME 			VARCHAR(200) 	DEFAULT '' COMMENT '英文名称',
 ORG_CODE 			VARCHAR(9) 	DEFAULT '' COMMENT '机构代码标识',
 ORG_TYPE 			VARCHAR(50) 	DEFAULT '' COMMENT '机构类型',
 PRINCIPAL_NAME 	VARCHAR(200) 	DEFAULT '' COMMENT '法人或负责人姓名',
 PRINCIPAL_ID_TYPE 	VARCHAR(10) 	DEFAULT '' COMMENT '法人或者负责人证件类型',
 PRINCIPAL_ID_NUM 	VARCHAR(50) 	DEFAULT '' COMMENT '法人或者负责人证件号码', 
 DESCRIPTION	 	VARCHAR(1000) 	DEFAULT '' COMMENT '描述',
 CREATED_DT 		DATETIME COMMENT '创建时间',
 IS_LEAF			INT COMMENT '叶子节点',
 VERSION 			INT 			DEFAULT 0 COMMENT '并发版本控制',
 STATUS 			INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用' ,
 TAB_INDEX 			INT 			DEFAULT 0 COMMENT '排序码',
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDX_ORG_ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='机构表'; 

--机构分类
CREATE TABLE TBL_CORE_ORG_CATEGORY (
 DB_ID 		VARCHAR(50) 	NOT NULL COMMENT '主键',
 CODE 		VARCHAR(50) 	NOT NULL COMMENT '唯一标识',
 NAME 		VARCHAR(100) 	DEFAULT '' COMMENT '名称',
 MASTER 	INT 			DEFAULT 0 COMMENT '是否主体; 1 : 主; 0 : 从',
 MARK 		VARCHAR(1000) 	DEFAULT '' COMMENT '备注',
 VERSION 			INT 			DEFAULT 0 COMMENT '并发版本控制',
 STATUS 			INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用' ,
 TAB_INDEX 			INT 			DEFAULT 0 COMMENT '排序码',
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDX_CATEGORY_CODE` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='机构分类表'; 
 
--角色表
CREATE TABLE TBL_CORE_ROLE (
 DB_ID 						VARCHAR(50) 	NOT NULL COMMENT '数据库主键',
 ORG_DB_ID 					VARCHAR(50) 	DEFAULT 0 COMMENT '机构表数据库DB_ID',
 ID 						VARCHAR(100) 	NOT NULL COMMENT '角色唯一标识',
 NAME 						VARCHAR(200) 	DEFAULT '' COMMENT '名称', 
 VERSION 			INT 			DEFAULT 0 COMMENT '并发版本控制',
 STATUS 			INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用' ,
 TAB_INDEX 			INT 			DEFAULT 0 COMMENT '排序码',
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDX_ROLE_ID` (`ORG_DB_ID`, `ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色表'; 

--角色与功能菜单关联表
CREATE TABLE TBL_CORE_ROLE_MENU_R (
 DB_ID 			VARCHAR(50) NOT NULL COMMENT  '数据库主键' ,
 MENU_DB_ID 	VARCHAR(50) NOT NULL COMMENT '功能菜单',
 ROLE_DB_ID 	VARCHAR(50) NOT NULL COMMENT '角色',
 STATUS 		INT 		DEFAULT 1  COMMENT '状态，1 启用 0 禁用，默认启用', 
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDINX_ROLE_MENU_R` (`MENU_DB_ID`, `ROLE_DB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色与功能菜单关联表';

--用户表
CREATE TABLE  TBL_CORE_USER (
 DB_ID  				VARCHAR(50) 	NOT NULL COMMENT '数据库主键',
 ID 					VARCHAR(100) 	NOT NULL COMMENT '用户ID，登陆名',
 NAME 					VARCHAR(200) 	DEFAULT '' COMMENT '用户名称',
 DISPLAY_NAME 			VARCHAR(200) 	DEFAULT '' COMMENT '用户显示的名称',
 USER_PASSWORD 			VARCHAR(100) 	DEFAULT NULL COMMENT '用户登陆密码',  
 ORG_DB_ID 				VARCHAR(50) 	DEFAULT 0 COMMENT '用户所属机构。TBL_CORE_ORG的主键DB_ID',
 VERSION 			INT 			DEFAULT 0 COMMENT '并发版本控制',
 STATUS 			INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用' ,
 TAB_INDEX 			INT 			DEFAULT 0 COMMENT '排序码',
 PRIMARY KEY (DB_ID) ,
 UNIQUE KEY `IDX_ORG_USER` (`ORG_DB_ID`, `ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统用户表';
 
--用户信息扩展表  
CREATE TABLE TBL_CORE_USER_EXT (
 DB_ID 				VARCHAR(50) 	NOT NULL COMMENT '数据库主键',
 CORE_USER_DB_ID 	VARCHAR(50) 	NOT NULL COMMENT '系统用户表主键',
 OFFICIAL 			INT 			DEFAULT 1 COMMENT '是否在编: 1 在编; 0 不在编; 默认 1',
 CAUID 				VARCHAR(200)  	DEFAULT '' COMMENT 'CA证书唯一标识',
 EMAIL 				VARCHAR(50)  	DEFAULT '' COMMENT '邮件地址',
 SEX 				VARCHAR(10)  	DEFAULT '' COMMENT '性别: "男", "女", "未知"',
 BIRTHDAY 			DATE COMMENT '出生日期',
 OFFICE_PHONE 		VARCHAR(20) 	DEFAULT '' COMMENT '办公电话',
 MOBILE_PHONE 		VARCHAR(50)  	DEFAULT '' COMMENT '移动电话',
 QQ 				VARCHAR(50)  	DEFAULT '' COMMENT 'QQ',
 WEIXIN 			VARCHAR(50)  	DEFAULT '' COMMENT '微信',
 IDEN_ID 			VARCHAR(50)  	DEFAULT '' COMMENT '身份证号',
 CREATED_DT 		DATE,
 TAB_INDEX 			INT 			DEFAULT 0 COMMENT '排序码',
 VERSION 			INT 			DEFAULT 0 COMMENT '并发版本控制',
 PRIMARY KEY (DB_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统用户扩展表'; 

--用户与用户组的关联表
CREATE TABLE TBL_CORE_USER_GROUP_R (
 DB_ID 			VARCHAR(50) 	NOT NULL COMMENT '数据库主键',
 USER_DB_ID 	VARCHAR(50) 	NOT NULL COMMENT  '用户表数据库主键',
 GROUP_DB_ID 	VARCHAR(50) 	NOT NULL COMMENT '用户组表数据库主键',
 STATUS 		INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用', 
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDX_USER_GROUP_R` (`USER_DB_ID`, `GROUP_DB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户组与角色的关联表'; 

--用户与角色的关联表
CREATE TABLE TBL_CORE_USER_ROLE_R (
 DB_ID 			VARCHAR(50) 	NOT NULL COMMENT '数据库主键',
 USER_DB_ID 	VARCHAR(50) 	NOT NULL COMMENT '用户表数据库主键',
 ROLE_DB_ID 	VARCHAR(50) 	NOT NULL COMMENT '角色表数据库主键',
 STATUS 		INT 			DEFAULT 1 COMMENT '状态，1 启用 0 禁用 默认为启用', 
 PRIMARY KEY (DB_ID),
 UNIQUE KEY `IDX_USER_ROLE_R` (`USER_DB_ID`, `ROLE_DB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户与角色的关联表'; 

--变量定义表
CREATE TABLE  TBL_CORE_VARIABLE 
(
 DB_ID 		VARCHAR(50) 	NOT NULL COMMENT '数据库主键', 
 CODE 		VARCHAR(50) 	DEFAULT '' COMMENT '变量名称',
 NAME 		VARCHAR(200) 	DEFAULT '' COMMENT '变量中文名称',
 TYPE 		VARCHAR(20) 	DEFAULT '' COMMENT '变量类型' ,
 SCOPE 		VARCHAR(50) 	DEFAULT '' COMMENT '范围',
 SYSTEM_ID	VARCHAR(50) COMMENT '系统',
 STATUS 	INT 			DEFAULT 1  COMMENT '状态，1 启用 0 禁用 默认为启用',
 VERSION 	INT 			DEFAULT 0 COMMENT '并发版本控制',
 PRIMARY KEY (DB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='变量定义表'; 

--变量类型表
 CREATE TABLE TBL_CORE_VARIABLE_TYPE
 (	
 DBID VARCHAR(50) NOT NULL, 
 CODE VARCHAR(50) DEFAULT '', 
 NAME VARCHAR(200) DEFAULT '',
 CURRENTYEAR  VARCHAR(4),
 STATUS INT DEFAULT 1, 
 TABINDEX INT DEFAULT 0, 
 PRIMARY KEY (DBID) 
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='变量类型表';  
