--1、TBL_CORE_ACT_ASSIGNEES
DROP TABLE TBL_CORE_ACT_ASSIGNEES;

--2、TBL_CORE_ACT_NODE
DROP TABLE TBL_CORE_ACT_NODE;

--4、TBL_CORE_BACK_LOG
DROP TABLE TBL_CORE_BACK_LOG;

--5、TBL_CORE_COMMON
DROP TABLE TBL_CORE_COMMON;

--6、TBL_CORE_DATA_AUTHORITY
DROP TABLE TBL_CORE_DATA_AUTHORITY;

--7、TBL_CORE_DATA_AUTHORITY_VALUE
DROP TABLE TBL_CORE_DATA_AUTHORITY_VALUE;

--8、TBL_CORE_DATA_COLUMN
DROP TABLE TBL_CORE_DATA_COLUMN;

--9、TBL_CORE_DATA_DEF
DROP TABLE TBL_CORE_DATA_DEF;

--10、TBL_CORE_DATA_EVENT_R
DROP TABLE TBL_CORE_DATA_EVENT_R;

--11、TBL_CORE_DATA_REF_R
DROP TABLE TBL_CORE_DATA_REF_R;

--12、TBL_CORE_DATA_VARIABLE_R
DROP TABLE TBL_CORE_DATA_VARIABLE_R;

--13 TBL_CORE_DATASOURCE
DROP TABLE TBL_CORE_DATASOURCE;

--14 TBL_CORE_EVENT
DROP TABLE TBL_CORE_EVENT;

--15 TBL_CORE_GROUP
DROP TABLE TBL_CORE_GROUP;

--16 TBL_CORE_GROUP_MENU_R
DROP TABLE TBL_CORE_GROUP_MENU_R;

--17 TBL_CORE_ROLE_GROUP_R
DROP TABLE TBL_CORE_ROLE_GROUP_R;

--18 TBL_CORE_ID
DROP TABLE TBL_CORE_ID;

--19 TBL_CORE_LOG
DROP TABLE TBL_CORE_LOG;

--20 TBL_CORE_MENU
DROP TABLE TBL_CORE_MENU;

--21 TBL_CORE_MESSAGE
DROP TABLE TBL_CORE_MESSAGE;

--22 TBL_CORE_ORG
DROP TABLE TBL_CORE_ORG;

--23 TBL_CORE_ORG_CATEGORY
DROP TABLE TBL_CORE_ORG_CATEGORY;

--24 TBL_CORE_ROLE
DROP TABLE TBL_CORE_ROLE;

--25 TBL_CORE_ROLE_MENU_R
DROP TABLE TBL_CORE_ROLE_MENU_R;

--26 TBL_CORE_USER
DROP TABLE TBL_CORE_USER;

--27 TBL_CORE_USER_EXT
DROP TABLE TBL_CORE_USER_EXT;

--28 TBL_CORE_USER_GROUP_R
DROP TABLE TBL_CORE_USER_GROUP_R;

--29 TBL_CORE_USER_ROLE_R
DROP TABLE TBL_CORE_USER_ROLE_R;

--30 TBL_CORE_VARIABLE
DROP TABLE TBL_CORE_VARIABLE;

--31 TBL_CORE_VARIABLE_TYPE
DROP TABLE TBL_CORE_VARIABLE_TYPE;
