--工作流流程节点设置表  
CREATE TABLE TBL_CORE_ACT_NODE (	
 DB_ID 						VARCHAR2(50) 	NOT NULL, 
 PROCESSDEFINITION_KEY 		VARCHAR2(100) 	DEFAULT '', 
 PROCESSDEFINITION_NAME 	VARCHAR2(200) 	DEFAULT '', 
 ACTIVITY_ID 				VARCHAR2(100) 	DEFAULT '', 
 ACTIVITY_NAME 				VARCHAR2(200) 	DEFAULT '', 
 ACTIVITY_TYPE 				VARCHAR2(50) 	DEFAULT '', 
 FORM_URL	 				VARCHAR2(100) 	DEFAULT '', 
 IS_MULTI_TASK 				INT 			DEFAULT 0, 
 IS_SEQUENTIAL				INT				DEFAULT 0,
 MUL_INS_COMPLET_CONDITION 	VARCHAR2(20) 	DEFAULT '', 
 TASK_LISTENER 				VARCHAR2(500), 
 VARIABLE_EXPRESSION 		VARCHAR2(500), 
 PRIMARY KEY (DB_ID) 
); 
COMMENT ON TABLE TBL_CORE_ACT_NODE 								IS '工作流流程节点设置表';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.DB_ID 						IS '主键';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.PROCESSDEFINITION_KEY 		IS '流程定义唯一标识符';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.PROCESSDEFINITION_NAME 		IS '流程定义名称';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.ACTIVITY_ID 				IS '节点ID';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.ACTIVITY_NAME 				IS '节点名称'; 
COMMENT ON COLUMN TBL_CORE_ACT_NODE.ACTIVITY_TYPE 				IS '节点类型';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.FORM_URL 					IS '业务表单URL';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.IS_MULTI_TASK 				IS '是否为多实例任务'; 
COMMENT ON COLUMN TBL_CORE_ACT_NODE.IS_SEQUENTIAL				IS	'是否顺序执行多实例任务';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.MUL_INS_COMPLET_CONDITION 	IS '多实例任务完成条件';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.TASK_LISTENER 				IS '事件监听器,JSON格式';
COMMENT ON COLUMN TBL_CORE_ACT_NODE.VARIABLE_EXPRESSION 		IS '变量表达式，JSON格式';

--工作流流程节点参与者表  
CREATE TABLE TBL_CORE_ACT_ASSIGNEES (	
 DB_ID 					VARCHAR2(50) 	NOT NULL,
 NODE_DB_ID 			VARCHAR2(50) 	NOT NULL,
 ASSIGNEE_DB_ID 		VARCHAR2(50) 	DEFAULT '',
 ASSIGNEE_ID 			VARCHAR2(100) 	DEFAULT '',
 ASSIGNEE_NAME	 		VARCHAR2(200) 	DEFAULT '', 
 ASSIGNEE_TYPE			VARCHAR2(10) 	DEFAULT '',  
 STATUS 				INT 			DEFAULT 1,
 PRIMARY KEY (DB_ID) 
);
COMMENT ON TABLE TBL_CORE_ACT_ASSIGNEES 					IS '工作流流程节点参与者表';
COMMENT ON COLUMN TBL_CORE_ACT_ASSIGNEES.DB_ID 				IS '主键';
COMMENT ON COLUMN TBL_CORE_ACT_ASSIGNEES.NODE_DB_ID 		IS '流程节点设置表主键(TBL_CORE_ACTIVITY_NODE的DB_ID)';
COMMENT ON COLUMN TBL_CORE_ACT_ASSIGNEES.ASSIGNEE_DB_ID		IS '节点参与值DB_ID';
COMMENT ON COLUMN TBL_CORE_ACT_ASSIGNEES.ASSIGNEE_ID 		IS '节点参与值ID';
COMMENT ON COLUMN TBL_CORE_ACT_ASSIGNEES.ASSIGNEE_NAME 		IS '节点参与者名称';
COMMENT ON COLUMN TBL_CORE_ACT_ASSIGNEES.ASSIGNEE_TYPE 		IS '节点参与者类型: USER, ROLE, GROUP';


--流程回退操作日志表
CREATE TABLE TBL_CORE_BACK_LOG (
 DB_ID 						VARCHAR2(50) 	NOT NULL   ,
 PROCESSDEFINITION_ID 		VARCHAR2(100) 	NOT NULL ,
 PROCESSINSTANCE_ID 		VARCHAR2(100) 	NOT NULL ,
 ACTIVITY_ID_FROM 			VARCHAR2(100) 	NOT NULL,
 ACTIVITY_NAME_FROM			VARCHAR2(200)   ,
 ACTIVITY_ID_TO 			VARCHAR2(100) 	NOT NULL,
 ACTIVITY_NAME_TO			VARCHAR2(200)	,
 OPERATOR 					VARCHAR2(100) 	NOT NULL,
 CREATE_TIME 				DATE 			DEFAULT SYSDATE ,
 IN_USE 					CHAR(1) 		DEFAULT 'Y' ,
 VERSION 					INT 			DEFAULT 0 , 
  PRIMARY KEY (DB_ID)
) ;
COMMENT ON TABLE TBL_CORE_BACK_LOG 							IS '流程回退操作日志表';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.DB_ID 					IS '主键';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.PROCESSDEFINITION_ID 	IS '流程模型ID';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.PROCESSINSTANCE_ID 		IS '流程实例ID';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.ACTIVITY_ID_TO 			IS '退回到的流程节点ID';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.ACTIVITY_NAME_TO 		IS '退回到的流程节点名称';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.ACTIVITY_ID_FROM 		IS '退回时的流程节点ID';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.ACTIVITY_NAME_FROM 		IS '退回时的流程节点名称';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.OPERATOR 				IS '操作：BACK（退回） CANCEL (撤销) ';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.CREATE_TIME 			IS '创建时间';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.IN_USE 					IS '是否有效，Y 有效， N 无效';
COMMENT ON COLUMN TBL_CORE_BACK_LOG.VERSION 				IS '并发操作的锁';

--系统全局变量表
CREATE TABLE  TBL_CORE_COMMON (  
 NAME 		VARCHAR2(200) DEFAULT '' ,
 VALUE_ 	VARCHAR2(200) DEFAULT '' ,
 TYPE_ 		VARCHAR2(200) DEFAULT '' ,
 STATUS 	INT DEFAULT 1 ,
 TAB_INDEX 	INT DEFAULT 0 ,
 PRIMARY KEY (NAME) 
);
COMMENT ON TABLE 	TBL_CORE_COMMON 				IS 	'系统全局变量表';
COMMENT ON COLUMN 	TBL_CORE_COMMON.NAME			IS	'名称';
COMMENT ON COLUMN 	TBL_CORE_COMMON.VALUE_			IS	'值';
COMMENT ON COLUMN 	TBL_CORE_COMMON.TYPE_			IS 	'类型'; 
COMMENT ON COLUMN 	TBL_CORE_COMMON.STATUS 			IS 	'状态: 1 启用;  0 禁用; 默认 1';
COMMENT ON COLUMN 	TBL_CORE_COMMON.TAB_INDEX 		IS 	'显示顺序';


--数据源设置表
CREATE TABLE  TBL_CORE_DATASOURCE (  
 DB_ID  			VARCHAR2(50) 	NOT NULL,
 DS_KEY 			VARCHAR2(100)  NOT NULL ,
 DB_TYPE 			VARCHAR2(50) DEFAULT '' ,
 DB_NAME 			VARCHAR2(50) DEFAULT '' ,
 DRIVER_CLASS 		VARCHAR2(100) DEFAULT '' ,
 JDBC_URL 			VARCHAR2(100) DEFAULT '' ,
 JDBC_USER 			VARCHAR2(50) DEFAULT '' ,
 JDBC_PASSWORD 		VARCHAR2(50) DEFAULT '' , 
 INIT_POOL_SIZE		INT,
 MIN_POOL_SIZE		INT,
 MAX_POOL_SIZE		INT,
 STATUS 			INT DEFAULT 1 ,
 TAB_INDEX 			INT DEFAULT 0 ,
 PRIMARY KEY (DB_ID) 
);
CREATE UNIQUE INDEX IDX_DSKEY ON TBL_CORE_DATASOURCE (DS_KEY);
COMMENT ON TABLE 	TBL_CORE_DATASOURCE 					IS 	'数据源设置表';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.DB_TYPE				IS	'数据库类型';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.DS_KEY				IS	'数据源标识名';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.DB_NAME				IS	'数据库名称';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.DRIVER_CLASS		IS	'数据库驱动类';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.JDBC_URL			IS	'数据库连接地址';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.JDBC_USER			IS	'数据库用户名';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.JDBC_PASSWORD		IS	'数据库密码';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.INIT_POOL_SIZE		IS	'数据库连接池初始值';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.MIN_POOL_SIZE		IS	'数据库连接池最小值';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.MAX_POOL_SIZE		IS 	'数据库连接池最大值'; 
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.STATUS 				IS 	'状态: 1 启用;  0 禁用; 默认 1';
COMMENT ON COLUMN 	TBL_CORE_DATASOURCE.TAB_INDEX 			IS 	'显示顺序';

-- 数据权限配置表
CREATE TABLE TBL_CORE_DATA_AUTHORITY (
 DB_ID 						VARCHAR2(50) NOT NULL,
 REF_R_DB_ID				VARCHAR2(50),
 DEF_DB_ID 					VARCHAR2(50) NOT NULL,
 COLUMN_DB_ID 				VARCHAR2(50),
 AUTHED_DB_ID 				VARCHAR2(50) ,
 AUTH_TYPE 					VARCHAR2(10) NOT NULL ,
 DATA_TYPE 					VARCHAR2(10) DEFAULT 'COMMON', 
 STATUS 					INT DEFAULT 1, 
 PRIMARY KEY (DB_ID)
);  
COMMENT ON TABLE TBL_CORE_DATA_AUTHORITY 				IS '数据权限设置表';
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY.DB_ID 		IS '数据库主键'; 
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY.REF_R_DB_ID 	IS '数据表TBL_CORE_DATA_REF_R主键';
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY.DEF_DB_ID 	IS '数据表TBL_WF_DATA_DEF主键';
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY.COLUMN_DB_ID 	IS '数据表TBL_WF_DATA_COLUMN主键';
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY.AUTHED_DB_ID 	IS '被授权者主键'; 
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY.AUTH_TYPE 	IS '授权类型（用户、角色或者用户组）';
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY.DATA_TYPE 	IS '数据类型，基础数据OR业务数据（COMMON OR BUSINESS）';
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY.STATUS 		IS '状态，1 启用 0 禁用，默认启用';


--基础数据权限要素值
CREATE TABLE TBL_CORE_DATA_AUTHORITY_VALUE
(	
    DB_ID   			VARCHAR2(50)   	NOT NULL,
	AUTHORITY_DB_ID 	VARCHAR2(50) 	NOT NULL , 
	DATA_VALUE 			VARCHAR2(200) 	NOT NULL ,
	STATUS 				INT 			DEFAULT 1,
	PRIMARY KEY (DB_ID)
); 
COMMENT ON TABLE TBL_CORE_DATA_AUTHORITY_VALUE 						IS '权限要素值表';
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY_VALUE.DB_ID 				IS '数据库主键';
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY_VALUE.AUTHORITY_DB_ID 	IS '权限要素设置表TBL_WF_DATA_AUTH_CONFIG的主键';
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY_VALUE.DATA_VALUE 			IS '授权数据的值'; 
COMMENT ON COLUMN TBL_CORE_DATA_AUTHORITY_VALUE.STATUS 				IS '状态，1 启用 0 禁用，默认启用';


--业务数据详细字段表 
CREATE TABLE TBL_CORE_DATA_COLUMN
(	
   	DB_ID 				VARCHAR2(50) 	NOT NULL, 
	DEF_DB_ID 			VARCHAR2(50) 	NOT NULL, 
	CODE 				VARCHAR2(100) 	NOT NULL, 
	NAME 				VARCHAR2(200) 	NOT NULL, 
	BEAN_FIELD_NAME		VARCHAR2(100) 	NOT NULL, 
	FIELD_SIZE 			INT 			NOT NULL, 
	FIELD_PRECISION		INT 			DEFAULT 0, 
	FIELD_TYPE 			VARCHAR2(50) 	DEFAULT '', 
	DEFAULT_VALUE	 	VARCHAR2(200), 
	FIELD_COMMENT 		VARCHAR2(500), 
	PRIMARY_FIELD 		INT 			DEFAULT 0, 
	QUOTE_FIELD			INT 			DEFAULT 0, 
	DISPLAY_FIELD		INT 			DEFAULT 0, 
	TREE_FIELD			INT 			DEFAULT 0, 
	RESOURCE_TYPE_CODE	VARCHAR2(50),  
	MARK 				VARCHAR2(1000), 
	QUERY_FIELD			INT 			DEFAULT 0, 
	MANDATORY_FIELD 	INT 			DEFAULT 0, 
	VALID_TYPE			VARCHAR2(100),
	MISSING_MESSAGE		VARCHAR2(500),
	INVALID_MESSAGE		VARCHAR2(500), 
	MIN_VALUE			VARCHAR2(100),
	MAX_VALUE			VARCHAR2(100),
	PRECISION_VALUE		VARCHAR2(100),
	DATA_OPTIONS		VARCHAR2(200),
	UNIQUE_FIELD		INT 			DEFAULT 0, 
	STATUS				INT DEFAULT 1, 
	VERSION				INT DEFAULT 0, 
	TAB_INDEX			INT DEFAULT 0, 
	PRIMARY KEY (DB_ID) 
);
COMMENT ON TABLE TBL_CORE_DATA_COLUMN 						IS '业务数据详细字段表';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.DB_ID 				IS '数据库自增，主键';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.DEF_DB_ID 			IS '数据定义表主键';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.CODE 				IS '字段名称';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.NAME 				IS '字段名称';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.BEAN_FIELD_NAME 		IS '字段别名';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.FIELD_SIZE 			IS '字段长度';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.FIELD_PRECISION 		IS '字段精度'; 
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.FIELD_TYPE 			IS '字段类型';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.FIELD_COMMENT 		IS '字段注释';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.MARK 				IS '备注说明信息';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.PRIMARY_FIELD 		IS '是否是主键，1为主键 ；0为否， 默认为非主键';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.QUERY_FIELD 			IS '是否是查询条件，1为是 ；0为否， 默认为否';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.UNIQUE_FIELD 		IS '是否唯一，1为是 ；0为否， 默认为否'; 
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.TREE_FIELD 			IS '是否树节点，1为是 ；0为否， 默认为否';  
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.QUOTE_FIELD 			IS '是否为引用字段，1为是 ；0为否， 默认为否'; 
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.DISPLAY_FIELD 		IS '是否为显示字段，1为是 ；0为否， 默认为是'; 
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.MANDATORY_FIELD 		IS '是否为必须输入字段，1为是 ；0为否， 默认为是';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.VALID_TYPE 			IS '验证类型';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.MISSING_MESSAGE 		IS '提示信息';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.INVALID_MESSAGE 		IS '无效提示信息';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.MIN_VALUE 			IS '最小值';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.MAX_VALUE 			IS '最大值';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.PRECISION_VALUE 		IS '精度';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.DATA_OPTIONS 		IS '自定义验证类型';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.DEFAULT_VALUE 		IS '字段的默认值'; 
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.RESOURCE_TYPE_CODE 	IS '资源类型与TBL_WF_RESOURCE_TYPE关联';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.STATUS 				IS '状态，1 启用 0 禁用 默认为启用';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.VERSION 				IS '并发版本控制';
COMMENT ON COLUMN TBL_CORE_DATA_COLUMN.TAB_INDEX 			IS '显示顺序';


--业务数据定义
CREATE TABLE TBL_CORE_DATA_DEF
(
 DB_ID 						VARCHAR2(50) 		NOT NULL ,
 ORG_DB_ID 					VARCHAR2(50) , 
 MENU_DB_ID 				VARCHAR2(50) , 
 CODE 						VARCHAR2(100) 		NOT NULL UNIQUE, 
 NAME 						VARCHAR2(200) ,
 DATA_TYPE 					VARCHAR2(50),
 AUTH_ENABLE				VARCHAR2(10)	DEFAULT 'N',
 TABLE_NAME 				VARCHAR2(100) ,
 TABLE_COMMENTS 			VARCHAR2(1000),
 MODEL_NAME 				VARCHAR2(100) ,
 PACKAGE_NAME 				VARCHAR2(100) ,
 CURRENT_YEAR 				VARCHAR2(10) ,
 TREE_TABLE 				INT 				DEFAULT 0 ,
 STATUS 					INT 				DEFAULT 1 , 
 VERSION 					INT 				DEFAULT 0 , 
 TAB_INDEX					INT					DEFAULT 0,
 PRIMARY KEY (DB_ID)
); 
COMMENT ON TABLE TBL_CORE_DATA_DEF 							IS '数据定义表';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.DB_ID 					IS '数据库主键';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.CODE 					IS '业务数据编码';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.NAME 					IS '业务数据名称';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.DATA_TYPE 				IS '数据类型(业务数据 OR 基础数据)';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.ORG_DB_ID 				IS '机构';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.MENU_DB_ID 				IS '功能菜单';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.AUTH_ENABLE				IS '是否是权限控制要素, Y : 是; N : 否';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.TABLE_NAME 				IS '对应的数据库表名称';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.TABLE_COMMENTS 			IS '对应的数据库表注释';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.MODEL_NAME 				IS '模块名称';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.PACKAGE_NAME 			IS '包名'; 
COMMENT ON COLUMN TBL_CORE_DATA_DEF.STATUS 					IS '状态，1 启用 0 禁用 默认为启用';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.TREE_TABLE 				IS '是否树形表格，1 是 0 否； 默认为否';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.VERSION 				IS '并发版本控制';
COMMENT ON COLUMN TBL_CORE_DATA_DEF.TAB_INDEX 				IS '排序码'; 


--数据与事件关联表
CREATE TABLE TBL_CORE_DATA_EVENT_R  (
   DB_ID                VARCHAR2(50)  	NOT NULL,
   DEF_DB_ID            VARCHAR2(50) 	NOT NULL,
   EVENT_DB_ID   		VARCHAR2(50)  	NOT NULL,
   STATUS 				INT 			DEFAULT 1  ,
   PRIMARY KEY (DB_ID)
);  
COMMENT ON TABLE TBL_CORE_DATA_EVENT_R 					IS '数据与事件关联表';
COMMENT ON COLUMN TBL_CORE_DATA_EVENT_R.DB_ID 			IS '主键';
COMMENT ON COLUMN TBL_CORE_DATA_EVENT_R.DEF_DB_ID 		IS '数据表主键';
COMMENT ON COLUMN TBL_CORE_DATA_EVENT_R.EVENT_DB_ID 	IS '事件表主键'; 
COMMENT ON COLUMN TBL_CORE_DATA_EVENT_R.STATUS 			IS '状态'; 


--数据引用关系表
CREATE TABLE TBL_CORE_DATA_REF_R  (
	DB_ID				VARCHAR2(50)    NOT NULL,
	DEF_DB_ID			VARCHAR2(50)	NOT NULL,
	COLUMN_DB_ID		VARCHAR2(50)	NOT NULL,
	REF_DB_ID			VARCHAR2(50)	NOT NULL,
	REF_COLUMN_DB_ID	VARCHAR2(50)	NOT NULL,
	DATA_AUTH_ENABLE	VARCHAR2(10)	DEFAULT 'N',
	PROCESS_AUTH_ENABLE	VARCHAR2(10)	DEFAULT 'N',
	PRIMARY KEY(DB_ID)
);  
COMMENT ON TABLE TBL_CORE_DATA_REF_R 						IS '数据引用关系表';
COMMENT ON COLUMN TBL_CORE_DATA_REF_R.DB_ID 				IS '主键';
COMMENT ON COLUMN TBL_CORE_DATA_REF_R.DEF_DB_ID 			IS '数据表TBL_WF_DATA_DEF主键';
COMMENT ON COLUMN TBL_CORE_DATA_REF_R.COLUMN_DB_ID 			IS '数据表TBL_WF_DATA_COLUMN主键';  
COMMENT ON COLUMN TBL_CORE_DATA_REF_R.REF_DB_ID 			IS '引用数据表TBL_WF_DATA_COLUMN主键'; 
COMMENT ON COLUMN TBL_CORE_DATA_REF_R.REF_COLUMN_DB_ID 		IS '引用数据表TBL_WF_DATA_COLUMN主键'; 
COMMENT ON COLUMN TBL_CORE_DATA_REF_R.DATA_AUTH_ENABLE 		IS '是否启用数据权限标志。 Y：启用； N：禁用； 默认N';  
COMMENT ON COLUMN TBL_CORE_DATA_REF_R.PROCESS_AUTH_ENABLE 	IS '是否用流程权限标志。 Y：启用； N：禁用； 默认N';  


--数据与变量关联表
CREATE TABLE TBL_CORE_DATA_VARIABLE_R  (
   DB_ID                VARCHAR2(50)  	NOT NULL,
   DEF_DB_ID            VARCHAR2(50) 	NOT NULL,
   VAR_DB_ID   			VARCHAR2(50)  	NOT NULL,
   STATUS 				INT 			DEFAULT 1  ,
   PRIMARY KEY (DB_ID)
);  
COMMENT ON TABLE TBL_CORE_DATA_VARIABLE_R 				IS '数据与变量关联表';
COMMENT ON COLUMN TBL_CORE_DATA_VARIABLE_R.DB_ID 		IS '主键';
COMMENT ON COLUMN TBL_CORE_DATA_VARIABLE_R.DEF_DB_ID 	IS '数据表主键';
COMMENT ON COLUMN TBL_CORE_DATA_VARIABLE_R.VAR_DB_ID 	IS '变量表主键'; 
COMMENT ON COLUMN TBL_CORE_DATA_VARIABLE_R.STATUS 		IS '状态'; 
 

--事件
CREATE TABLE TBL_CORE_EVENT  
(
   DB_ID                VARCHAR2(50)  	NOT NULL,
   CODE            		VARCHAR2(100) 	NOT NULL,
   NAME   				VARCHAR2(100), 
   SYSTEM_ID			VARCHAR2(50),
   CLASS_NAME         	VARCHAR2(100),
   SPRING_BEAN_ID 		VARCHAR2(100),
   METHOD_NAME          VARCHAR2(50),
   STATUS 				INT 			DEFAULT 1  ,
   EVENT_TYPE           VARCHAR2(50), 
   PRIMARY KEY (DB_ID)
); 
COMMENT ON TABLE TBL_CORE_EVENT 					IS '事件表';
COMMENT ON COLUMN TBL_CORE_EVENT.DB_ID 				IS '主键';
COMMENT ON COLUMN TBL_CORE_EVENT.CODE 				IS '编码';
COMMENT ON COLUMN TBL_CORE_EVENT.NAME 				IS '名称';
COMMENT ON COLUMN TBL_CORE_EVENT.SYSTEM_ID 			IS '系统';
COMMENT ON COLUMN TBL_CORE_EVENT.CLASS_NAME 		IS 'JAVA类名';
COMMENT ON COLUMN TBL_CORE_EVENT.SPRING_BEAN_ID 	IS 'SPRING中ID'; 
COMMENT ON COLUMN TBL_CORE_EVENT.METHOD_NAME 		IS '方法名';
COMMENT ON COLUMN TBL_CORE_EVENT.EVENT_TYPE 		IS '类型'; 
COMMENT ON COLUMN TBL_CORE_EVENT.STATUS 			IS '状态';


--用户组
CREATE TABLE TBL_CORE_GROUP (
 DB_ID 				VARCHAR2(50) 	NOT NULL , 
 ID 				VARCHAR2(100) 	NOT NULL,
 NAME	 			VARCHAR2(200) 	DEFAULT '' ,
 DESCRIPTION 		VARCHAR2(1000) 	DEFAULT '',
 CREATED_DT 		DATE,
 VERSION 			INT 			DEFAULT 0 ,
 STATUS 			INT 			DEFAULT 1 ,
 TAB_INDEX 			INT 			DEFAULT 0 ,
 PRIMARY KEY (DB_ID)
);
COMMENT ON TABLE TBL_CORE_GROUP 					IS '用户组表';
COMMENT ON COLUMN TBL_CORE_GROUP.DB_ID 				IS '数据库主键'; 
COMMENT ON COLUMN TBL_CORE_GROUP.ID 				IS '唯一标识';
COMMENT ON COLUMN TBL_CORE_GROUP.NAME 				IS '中文名称';
COMMENT ON COLUMN TBL_CORE_GROUP.DESCRIPTION 		IS '描述';
COMMENT ON COLUMN TBL_CORE_GROUP.CREATED_DT 		IS '创建时间';
COMMENT ON COLUMN TBL_CORE_GROUP.VERSION 			IS '并发版本控制';
COMMENT ON COLUMN TBL_CORE_GROUP.STATUS 			IS '状态，1 启用 0 禁用 默认为启用';
COMMENT ON COLUMN TBL_CORE_GROUP.TAB_INDEX 			IS '显示顺序号';


--用户组与功能菜单关联表
CREATE TABLE TBL_CORE_GROUP_MENU_R (
 DB_ID 			VARCHAR2(50) NOT NULL  ,
 MENU_DB_ID 	VARCHAR2(50) NOT NULL ,
 GROUP_DB_ID 	VARCHAR2(50) NOT NULL ,
 STATUS 		INT 		DEFAULT 1  , 
 PRIMARY KEY (DB_ID)
);
CREATE UNIQUE INDEX IDINX_GROUP_MENU_R ON TBL_CORE_GROUP_MENU_R (MENU_DB_ID, GROUP_DB_ID);
COMMENT ON TABLE TBL_CORE_GROUP_MENU_R 					IS '角色与功能菜单关联表';
COMMENT ON COLUMN TBL_CORE_GROUP_MENU_R.DB_ID 			IS '数据库主键';
COMMENT ON COLUMN TBL_CORE_GROUP_MENU_R.MENU_DB_ID 		IS '功能菜单';
COMMENT ON COLUMN TBL_CORE_GROUP_MENU_R.GROUP_DB_ID 		IS '用户组';
COMMENT ON COLUMN TBL_CORE_GROUP_MENU_R.STATUS 			IS '状态，1 启用 0 禁用，默认启用';


--用户组与角色的关联表
CREATE TABLE TBL_CORE_ROLE_GROUP_R (
 DB_ID 			VARCHAR2(50) 	NOT NULL ,
 GROUP_DB_ID 	VARCHAR2(50) 	NOT NULL ,
 ROLE_DB_ID 	VARCHAR2(50) 	NOT NULL ,
 STATUS 		INT 			DEFAULT 1 , 
 PRIMARY KEY (DB_ID) 
);
CREATE UNIQUE INDEX IDX_GROUP_ROLE_R ON TBL_CORE_ROLE_GROUP_R (GROUP_DB_ID, ROLE_DB_ID);
COMMENT ON TABLE TBL_CORE_ROLE_GROUP_R 					IS '用户组与角色的关联表';
COMMENT ON COLUMN TBL_CORE_ROLE_GROUP_R.DB_ID 			IS '数据库主键';
COMMENT ON COLUMN TBL_CORE_ROLE_GROUP_R.GROUP_DB_ID 	IS '用户组表数据库自增，主键';
COMMENT ON COLUMN TBL_CORE_ROLE_GROUP_R.ROLE_DB_ID 		IS '角色表数据库自增，主键';
COMMENT ON COLUMN TBL_CORE_ROLE_GROUP_R.STATUS 			IS '状态，1 启用 0 禁用 默认为启用';


--序列号
CREATE TABLE TBL_CORE_ID (
 DB_ID      VARCHAR2(50) NOT NULL,
 KEY_ 		VARCHAR2(255) NOT NULL,
 VALUE_ 	VARCHAR2(255) DEFAULT NULL , 
 PRIMARY 	KEY (DB_ID)
);
COMMENT ON TABLE  TBL_CORE_ID 			IS '序列号表';
COMMENT ON COLUMN TBL_CORE_ID.KEY_ 		IS '生成序列号KEY';
COMMENT ON COLUMN TBL_CORE_ID.VALUE_ 	IS '当前序列号值';

--日志表
CREATE TABLE TBL_CORE_LOG (
 DBID 						VARCHAR2(50) 	NOT NULL   ,
 MODELNAME				 	VARCHAR2(200) 	NOT NULL ,
 USERID 					VARCHAR2(100) 	NOT NULL ,
 USERNAME 					VARCHAR2(1000) 	NOT NULL,
 OPERATOR					VARCHAR2(1000),
 BUSINESSKEY				VARCHAR2(50)	NOT NULL,
 OPERATETIME 				DATE, 
  PRIMARY KEY (DBID)
);
COMMENT ON TABLE TBL_CORE_LOG 							IS '业务操作日志表';
COMMENT ON COLUMN TBL_CORE_LOG.DBID 					IS '主键';
COMMENT ON COLUMN TBL_CORE_LOG.MODELNAME 				IS '模块名';
COMMENT ON COLUMN TBL_CORE_LOG.USERID 					IS '操作者ID';
COMMENT ON COLUMN TBL_CORE_LOG.USERNAME 				IS '操作者名称';
COMMENT ON COLUMN TBL_CORE_LOG.OPERATOR 				IS '操作';
COMMENT ON COLUMN TBL_CORE_LOG.OPERATETIME 				IS '操作时间';


--功能菜单表
CREATE TABLE TBL_CORE_MENU (
 DB_ID 			VARCHAR2(50) 	NOT NULL ,
 PARENT_DB_ID 	VARCHAR2(50)  	DEFAULT 0  ,
 ORG_DB_ID 		VARCHAR2(50),
 ID 			VARCHAR2(100) 	NOT NULL UNIQUE,
 NAME 			VARCHAR2(200) 	DEFAULT '' , 
 URL 			VARCHAR2(500) 	DEFAULT '' , 
 MENU_TYPE		VARCHAR2(20),	
 IS_LEAF 		INT 			DEFAULT 0 ,
 VERSION 		INT 			DEFAULT 0 ,
 STATUS 		INT 			DEFAULT 1 ,
 TAB_INDEX 		INT 			DEFAULT 0 ,
 PRIMARY KEY (DB_ID) 
); 
COMMENT ON TABLE TBL_CORE_MENU 					IS '功能菜单表';
COMMENT ON COLUMN TBL_CORE_MENU.DB_ID 			IS '数据库主键';
COMMENT ON COLUMN TBL_CORE_MENU.PARENT_DB_ID	IS '上级节点数据库DB_ID';
COMMENT ON COLUMN TBL_CORE_MENU.ORG_DB_ID 		IS '所属机构数据库主键';
COMMENT ON COLUMN TBL_CORE_MENU.ID 				IS '资源标识符';
COMMENT ON COLUMN TBL_CORE_MENU.NAME 			IS '资源名称';
COMMENT ON COLUMN TBL_CORE_MENU.URL 			IS '连接地址';
COMMENT ON COLUMN TBL_CORE_MENU.MENU_TYPE 		IS '菜单类型';
COMMENT ON COLUMN TBL_CORE_MENU.IS_LEAF 		IS '是否叶子节点，1 是 0 否，默认否';
COMMENT ON COLUMN TBL_CORE_MENU.VERSION 		IS '版本号';
COMMENT ON COLUMN TBL_CORE_MENU.STATUS	 		IS '状态，1 启用 0 禁用，默认启用';
COMMENT ON COLUMN TBL_CORE_MENU.TAB_INDEX 		IS '显示顺序号';


--流程回退操作日志表
CREATE TABLE TBL_CORE_MESSAGE (
 DB_ID 						VARCHAR2(50) 	NOT NULL   ,
 TITLE				 		VARCHAR2(200) 	NOT NULL ,
 SENDER 					VARCHAR2(100) 	NOT NULL ,
 RECEIVER 					VARCHAR2(1000) 	NOT NULL,
 CONTENT					VARCHAR2(1000),
 SEND_TIME 					DATE,
 CREATE_TIME 				DATE 			DEFAULT SYSDATE ,
 STATUS 					INT 			DEFAULT 0 , 
  PRIMARY KEY (DB_ID)
);
COMMENT ON TABLE TBL_CORE_MESSAGE 							IS '系统信息表';
COMMENT ON COLUMN TBL_CORE_MESSAGE.DB_ID 					IS '主键';
COMMENT ON COLUMN TBL_CORE_MESSAGE.TITLE 					IS '标题';
COMMENT ON COLUMN TBL_CORE_MESSAGE.SENDER 					IS '发送者';
COMMENT ON COLUMN TBL_CORE_MESSAGE.RECEIVER 				IS '接收者';
COMMENT ON COLUMN TBL_CORE_MESSAGE.CONTENT 					IS '内容';
COMMENT ON COLUMN TBL_CORE_MESSAGE.SEND_TIME 				IS '发送时间';
COMMENT ON COLUMN TBL_CORE_MESSAGE.CREATE_TIME 				IS '创建时间';
COMMENT ON COLUMN TBL_CORE_MESSAGE.STATUS 					IS '发送状态。1：已发送；0：未发送';


--机构--机构
CREATE TABLE TBL_CORE_ORG (
 DB_ID 				VARCHAR2(50) 	NOT NULL , 
 PARENT_DB_ID		VARCHAR2(50)    NOT NULL,
 CATEGORY_DB_ID		VARCHAR2(50),
 ID 				VARCHAR2(100) 	NOT NULL  UNIQUE,
 NAME 				VARCHAR2(200) 	DEFAULT '' ,
 ENNAME 			VARCHAR2(200) 	DEFAULT '' ,
 ORG_CODE 			VARCHAR2(9) 	DEFAULT '' ,
 ORG_TYPE 			VARCHAR2(50) 	DEFAULT '' ,
 PRINCIPAL_NAME 	VARCHAR2(200) 	DEFAULT '' ,
 PRINCIPAL_ID_TYPE 	VARCHAR2(10) 	DEFAULT '' ,
 PRINCIPAL_ID_NUM 	VARCHAR2(50) 	DEFAULT '' , 
 DESCRIPTION	 	VARCHAR2(1000) 	DEFAULT '' ,
 CREATED_DT 		DATE,
 IS_LEAF			INT,
 VERSION 			INT 			DEFAULT 0 ,
 STATUS 			INT 			DEFAULT 1 ,
 TAB_INDEX 			INT 			DEFAULT 0 ,
 PRIMARY KEY (DB_ID)
); 
COMMENT ON TABLE TBL_CORE_ORG 						IS '机构表'; 
COMMENT ON COLUMN TBL_CORE_ORG.DB_ID 				IS '数据库主键'; 
COMMENT ON COLUMN TBL_CORE_ORG.PARENT_DB_ID 		IS '上级节点'; 
COMMENT ON COLUMN TBL_CORE_ORG.CATEGORY_DB_ID 		IS '机构分类'; 
COMMENT ON COLUMN TBL_CORE_ORG.ID 					IS '唯一标识';
COMMENT ON COLUMN TBL_CORE_ORG.NAME 				IS '中文名称';
COMMENT ON COLUMN TBL_CORE_ORG.ENNAME 				IS '英文名称';
COMMENT ON COLUMN TBL_CORE_ORG.ORG_CODE 			IS '机构代码标识';
COMMENT ON COLUMN TBL_CORE_ORG.ORG_TYPE 			IS '机构类型';
COMMENT ON COLUMN TBL_CORE_ORG.PRINCIPAL_NAME 		IS '法人或负责人姓名';
COMMENT ON COLUMN TBL_CORE_ORG.PRINCIPAL_ID_TYPE 	IS '法人或者负责人证件类型';
COMMENT ON COLUMN TBL_CORE_ORG.PRINCIPAL_ID_NUM 	IS '法人或者负责人证件号码';
COMMENT ON COLUMN TBL_CORE_ORG.DESCRIPTION 			IS '描述';
COMMENT ON COLUMN TBL_CORE_ORG.CREATED_DT 			IS '创建时间';
COMMENT ON COLUMN TBL_CORE_ORG.IS_LEAF 				IS '叶子节点';
COMMENT ON COLUMN TBL_CORE_ORG.VERSION 				IS '并发版本控制';
COMMENT ON COLUMN TBL_CORE_ORG.STATUS 				IS '状态: 1 启用;  0 禁用; 默认 1';
COMMENT ON COLUMN TBL_CORE_ORG.TAB_INDEX 			IS '显示顺序号';

--机构分类
CREATE TABLE TBL_CORE_ORG_CATEGORY (
 DB_ID 		VARCHAR2(50) 	NOT NULL,
 CODE 		VARCHAR2(50) 	NOT NULL UNIQUE,
 NAME 		VARCHAR2(100) 	DEFAULT '',
 MASTER 	INT 			DEFAULT 0,
 MARK 		VARCHAR2(1000) 	DEFAULT '',
 VERSION 	INT 			DEFAULT 0,
 STATUS 	INT DEFAULT 1 ,
 TAB_INDEX 	INT DEFAULT 0 ,
 PRIMARY KEY (DB_ID)
); 
COMMENT ON TABLE  TBL_CORE_ORG_CATEGORY  			IS  '抽象角色分类表';
COMMENT ON COLUMN TBL_CORE_ORG_CATEGORY.DB_ID 		IS 	'主键';
COMMENT ON COLUMN TBL_CORE_ORG_CATEGORY.CODE		IS	'唯一标识';
COMMENT ON COLUMN TBL_CORE_ORG_CATEGORY.NAME		IS	'名称';
COMMENT ON COLUMN TBL_CORE_ORG_CATEGORY.MASTER		IS	'是否主体; 1 : 主; 0 : 从';
COMMENT ON COLUMN TBL_CORE_ORG_CATEGORY.MARK		IS	'备注';
COMMENT ON COLUMN TBL_CORE_ORG_CATEGORY.STATUS 		IS 	'状态: 1 启用;  0 禁用; 默认 1';
COMMENT ON COLUMN TBL_CORE_ORG_CATEGORY.TAB_INDEX 	IS 	'显示顺序';


--角色表
CREATE TABLE TBL_CORE_ROLE (
 DB_ID 						VARCHAR2(50) 	NOT NULL,
 ORG_DB_ID 					VARCHAR2(50) 	DEFAULT 0,
 ID 						VARCHAR2(100) 	NOT NULL,
 NAME 						VARCHAR2(200) 	DEFAULT '', 
 VERSION 					INT 			DEFAULT 0,
 STATUS 					INT 			DEFAULT 1 ,
 TAB_INDEX 					INT 			DEFAULT 0,
 PRIMARY KEY (DB_ID) 
); 
CREATE UNIQUE INDEX IDX_ROLE_ID ON TBL_CORE_ROLE (ORG_DB_ID, ID);
COMMENT ON TABLE TBL_CORE_ROLE 								IS '角色表';
COMMENT ON COLUMN TBL_CORE_ROLE.DB_ID 						IS '数据库主键';
COMMENT ON COLUMN TBL_CORE_ROLE.ORG_DB_ID 					IS '机构表数据库DB_ID';
COMMENT ON COLUMN TBL_CORE_ROLE.ID 							IS '角色唯一标识';
COMMENT ON COLUMN TBL_CORE_ROLE.NAME 						IS '名称';  
COMMENT ON COLUMN TBL_CORE_ROLE.VERSION 					IS '版本号';
COMMENT ON COLUMN TBL_CORE_ROLE.STATUS 						IS '状态，1 启用 0 禁用 默认为启用';
COMMENT ON COLUMN TBL_CORE_ROLE.TAB_INDEX 					IS '显示顺序号';


--角色与功能菜单关联表
CREATE TABLE TBL_CORE_ROLE_MENU_R (
 DB_ID 			VARCHAR2(50) NOT NULL  ,
 MENU_DB_ID 	VARCHAR2(50) NOT NULL ,
 ROLE_DB_ID 	VARCHAR2(50) NOT NULL ,
 STATUS 		INT 		DEFAULT 1  , 
 PRIMARY KEY (DB_ID)
);
CREATE UNIQUE INDEX IDINX_ROLE_MENU_R ON TBL_CORE_ROLE_MENU_R (MENU_DB_ID, ROLE_DB_ID);
COMMENT ON TABLE TBL_CORE_ROLE_MENU_R 					IS '角色与功能菜单关联表';
COMMENT ON COLUMN TBL_CORE_ROLE_MENU_R.DB_ID 			IS '数据库主键';
COMMENT ON COLUMN TBL_CORE_ROLE_MENU_R.MENU_DB_ID 		IS '功能菜单';
COMMENT ON COLUMN TBL_CORE_ROLE_MENU_R.ROLE_DB_ID 		IS '角色';
COMMENT ON COLUMN TBL_CORE_ROLE_MENU_R.STATUS 			IS '状态，1 启用 0 禁用，默认启用';


--用户表
CREATE TABLE  TBL_CORE_USER (
 DB_ID  				VARCHAR2(50) 	NOT NULL,
 ID 					VARCHAR2(100) 	NOT NULL ,
 NAME 					VARCHAR2(200) 	DEFAULT '' ,
 DISPLAY_NAME 			VARCHAR2(200) 	DEFAULT '',
 USER_PASSWORD 			VARCHAR2(100) 	DEFAULT NULL ,  
 ORG_DB_ID 				VARCHAR2(50) 	DEFAULT 0,
 VERSION 				INT 			DEFAULT 0 ,
 STATUS 				INT 			DEFAULT 1 ,
 TAB_INDEX 				INT 			DEFAULT 0 ,
 PRIMARY KEY (DB_ID) 
);
--用户标识（ID）必须唯一
CREATE UNIQUE INDEX IDX_ORG_USER ON TBL_CORE_USER (ORG_DB_ID, ID);
COMMENT ON TABLE 	TBL_CORE_USER 					IS 		'系统用户表';
COMMENT ON COLUMN 	TBL_CORE_USER.DB_ID 			IS 		'数据库主键';
COMMENT ON COLUMN 	TBL_CORE_USER.ID				IS		'用户ID，登陆名';
COMMENT ON COLUMN 	TBL_CORE_USER.NAME				IS		'用户名称';
COMMENT ON COLUMN 	TBL_CORE_USER.DISPLAY_NAME		IS		'用户显示的名称';
COMMENT ON COLUMN 	TBL_CORE_USER.USER_PASSWORD		IS 		'用户登陆密码'; 
COMMENT ON COLUMN 	TBL_CORE_USER.ORG_DB_ID 		IS 		'TBL_CORE_ORG的主键DB_ID';
COMMENT ON COLUMN 	TBL_CORE_USER.VERSION 			IS 		'并发版本控制';
COMMENT ON COLUMN 	TBL_CORE_USER.STATUS 			IS 		'状态: 1 启用; 0 禁用; 默认 1';
COMMENT ON COLUMN 	TBL_CORE_USER.TAB_INDEX 		IS 		'显示顺序';


--用户信息扩展表  
CREATE TABLE TBL_CORE_USER_EXT (
 DB_ID 				VARCHAR2(50) 	NOT NULL,
 CORE_USER_DB_ID 	VARCHAR2(50) 	NOT NULL,
 OFFICIAL 			INT 			DEFAULT 1,
 CAUID 				VARCHAR2(200)  	DEFAULT '',
 EMAIL 				VARCHAR2(50)  	DEFAULT '',
 SEX 				VARCHAR2(10)  	DEFAULT '',
 BIRTHDAY 			DATE,
 OFFICE_PHONE 		VARCHAR2(20) 	DEFAULT '',
 MOBILE_PHONE 		VARCHAR2(50)  	DEFAULT '',
 QQ 				VARCHAR2(50)  	DEFAULT '',
 WEIXIN 			VARCHAR2(50)  	DEFAULT '',
 IDEN_ID 			VARCHAR2(50)  	DEFAULT '',
 TAB_INDEX 			INT 			DEFAULT 0,
 CREATED_DT 		DATE,
 VERSION 			INT 			DEFAULT 0, 
 PRIMARY KEY (DB_ID) 
); 
COMMENT ON TABLE TBL_CORE_USER_EXT 					IS  	'用户信息表';
COMMENT ON COLUMN TBL_CORE_USER_EXT.DB_ID 			IS 		'数据库主键';
COMMENT ON COLUMN TBL_CORE_USER_EXT.CORE_USER_DB_ID IS  	'系统用户表主键';
COMMENT ON COLUMN TBL_CORE_USER_EXT.OFFICIAL		IS		'是否在编: 1 在编; 0 不在编; 默认 1';
COMMENT ON COLUMN TBL_CORE_USER_EXT.CAUID			IS		'CA证书唯一标识';
COMMENT ON COLUMN TBL_CORE_USER_EXT.EMAIL			IS		'邮件地址';
COMMENT ON COLUMN TBL_CORE_USER_EXT.SEX 			IS		'性别: "男", "女", "未知"';
COMMENT ON COLUMN TBL_CORE_USER_EXT.BIRTHDAY		IS		'出生日期';
COMMENT ON COLUMN TBL_CORE_USER_EXT.OFFICE_PHONE	IS		'办公电话';
COMMENT ON COLUMN TBL_CORE_USER_EXT.MOBILE_PHONE	IS		'移动电话';
COMMENT ON COLUMN TBL_CORE_USER_EXT.QQ				IS		'QQ';
COMMENT ON COLUMN TBL_CORE_USER_EXT.WEIXIN			IS		'微信';
COMMENT ON COLUMN TBL_CORE_USER_EXT.IDEN_ID			IS		'身份证号';
COMMENT ON COLUMN TBL_CORE_USER_EXT.TAB_INDEX		IS		'显示顺序号';
COMMENT ON COLUMN TBL_CORE_USER_EXT.CREATED_DT		IS		'创建时间';
COMMENT ON COLUMN TBL_CORE_USER_EXT.VERSION			IS	 	'并发版本控制'; 


--用户与用户组的关联表
CREATE TABLE TBL_CORE_USER_GROUP_R (
 DB_ID 			VARCHAR2(50) 	NOT NULL ,
 USER_DB_ID 	VARCHAR2(50) 	NOT NULL ,
 GROUP_DB_ID 	VARCHAR2(50) 	NOT NULL ,
 STATUS 		INT 			DEFAULT 1 , 
 PRIMARY KEY (DB_ID) 
);
CREATE UNIQUE INDEX IDX_USER_GROUP_R ON TBL_CORE_USER_GROUP_R (USER_DB_ID, GROUP_DB_ID);
COMMENT ON TABLE TBL_CORE_USER_GROUP_R 					IS '用户组与角色的关联表';
COMMENT ON COLUMN TBL_CORE_USER_GROUP_R.DB_ID 			IS '数据库主键';
COMMENT ON COLUMN TBL_CORE_USER_GROUP_R.USER_DB_ID 		IS '用户表数据库自增，主键';
COMMENT ON COLUMN TBL_CORE_USER_GROUP_R.GROUP_DB_ID 	IS '用户组表数据库自增，主键';
COMMENT ON COLUMN TBL_CORE_USER_GROUP_R.STATUS 			IS '状态，1 启用 0 禁用 默认为启用';


--用户与角色的关联表
CREATE TABLE TBL_CORE_USER_ROLE_R (
 DB_ID 			VARCHAR2(50) 	NOT NULL ,
 USER_DB_ID 	VARCHAR2(50) 	NOT NULL ,
 ROLE_DB_ID 	VARCHAR2(50) 	NOT NULL ,
 STATUS 		INT 			DEFAULT 1 , 
 PRIMARY KEY (DB_ID) 
);
CREATE UNIQUE INDEX IDX_USER_ROLE_R ON TBL_CORE_USER_ROLE_R (USER_DB_ID, ROLE_DB_ID);
COMMENT ON TABLE TBL_CORE_USER_ROLE_R 				IS '用户与角色的关联表';
COMMENT ON COLUMN TBL_CORE_USER_ROLE_R.DB_ID 		IS '数据库主键';
COMMENT ON COLUMN TBL_CORE_USER_ROLE_R.USER_DB_ID 	IS '用户表数据库自增，主键';
COMMENT ON COLUMN TBL_CORE_USER_ROLE_R.ROLE_DB_ID 	IS '角色表数据库自增，主键';
COMMENT ON COLUMN TBL_CORE_USER_ROLE_R.STATUS 		IS '状态，1 启用 0 禁用 默认为启用';


--变量定义表
CREATE TABLE  TBL_CORE_VARIABLE 
(
 DB_ID 		VARCHAR2(50) 	NOT NULL , 
 CODE 		VARCHAR2(50) 	DEFAULT '' ,
 NAME 		VARCHAR2(200) 	DEFAULT '',
 TYPE 		VARCHAR2(20) 	DEFAULT '' ,
 SCOPE 		VARCHAR2(50) 	DEFAULT '' ,
 SYSTEM_ID	VARCHAR2(50),
 STATUS 	INT 			DEFAULT 1  ,
 VERSION 	INT 			DEFAULT 0 ,
 PRIMARY KEY (DB_ID)
);
COMMENT ON TABLE TBL_CORE_VARIABLE  			IS '变量定义表' ; 
COMMENT ON COLUMN TBL_CORE_VARIABLE.DB_ID 		IS '数据库主键'; 
COMMENT ON COLUMN TBL_CORE_VARIABLE.CODE 	IS '变量名称';
COMMENT ON COLUMN TBL_CORE_VARIABLE.NAME 	IS '变量中文名称';
COMMENT ON COLUMN TBL_CORE_VARIABLE.TYPE 	IS '变量类型';
COMMENT ON COLUMN TBL_CORE_VARIABLE.SCOPE 		IS '范围';
COMMENT ON COLUMN TBL_CORE_VARIABLE.SYSTEM_ID 	IS '系统';
COMMENT ON COLUMN TBL_CORE_VARIABLE.STATUS 		IS '状态';
COMMENT ON COLUMN TBL_CORE_VARIABLE.VERSION 	IS '并发版本控制';

--变量类型表
 CREATE TABLE TBL_CORE_VARIABLE_TYPE
 (	
 DBID VARCHAR2(50) NOT NULL, 
 CODE VARCHAR2(50) DEFAULT '', 
 NAME VARCHAR2(200) DEFAULT '',
 CURRENTYEAR  VARCHAR2(4),
 STATUS INT DEFAULT 1, 
 TABINDEX INT DEFAULT 0, 
 PRIMARY KEY (DBID) 
 );  
